//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_articulos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbAseguradoraEntities : DbContext
    {
        public dbAseguradoraEntities()
            : base("name=dbAseguradoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbDanio> tbDanio { get; set; }
        public virtual DbSet<tbDanioResolucion> tbDanioResolucion { get; set; }
        public virtual DbSet<tbPersona> tbPersona { get; set; }
        public virtual DbSet<tbReclamo> tbReclamo { get; set; }
        public virtual DbSet<tbSeguro> tbSeguro { get; set; }
        public virtual DbSet<tbVehiculo> tbVehiculo { get; set; }
        public virtual DbSet<tbResolucion> tbResolucion { get; set; }
        public virtual DbSet<tbChiCuadrada> tbChiCuadrada { get; set; }
    }
}
