//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDanioResolucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbDanioResolucion()
        {
            this.tbReclamo = new HashSet<tbReclamo>();
        }
    
        public int codDanio { get; set; }
        public int codResolucion { get; set; }
        public int codDanioResolucion { get; set; }
    
        public virtual tbDanio tbDanio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReclamo> tbReclamo { get; set; }
        public virtual tbResolucion tbResolucion { get; set; }
    }
}
