//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbReclamo
    {
        public int codReclamo { get; set; }
        public Nullable<int> codSeguro { get; set; }
        public Nullable<int> codEstado { get; set; }
        public Nullable<int> codDanioResolucion { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual tbDanioResolucion tbDanioResolucion { get; set; }
        public virtual tbSeguro tbSeguro { get; set; }
    }
}
