//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbResolucion
    {
        public int codResolucion { get; set; }
        public Nullable<int> codReclamo { get; set; }
        public string resolucion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual tbReclamo tbReclamo { get; set; }
    }
}
