//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_de_articulos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSeguro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSeguro()
        {
            this.tbReclamo = new HashSet<tbReclamo>();
        }
    
        public int codSeguro { get; set; }
        public Nullable<int> codPersona { get; set; }
        public Nullable<int> codVehiculo { get; set; }
        public Nullable<int> codEstado { get; set; }
        public Nullable<decimal> pagoMensual { get; set; }
        public Nullable<System.DateTime> fechaCreación { get; set; }
        public Nullable<decimal> deducible { get; set; }
    
        public virtual tbPersona tbPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbReclamo> tbReclamo { get; set; }
        public virtual tbVehiculo tbVehiculo { get; set; }
    }
}
